version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-todo-app
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app
    ports:
      - "4000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: nestjs-todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
